// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYKVyR6utmdUf5JeIU2FE3ApyTzYaHjQ',
    appId: '1:109222307798:web:cd9f02e5d9ad7df1c42677',
    messagingSenderId: '109222307798',
    projectId: 'code-academy-eed0d',
    authDomain: 'code-academy-eed0d.firebaseapp.com',
    storageBucket: 'code-academy-eed0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwwnYF32j9RtIMEtpXLU4njY55ZHFwdE',
    appId: '1:109222307798:android:1dbe58cc67b1ed9ac42677',
    messagingSenderId: '109222307798',
    projectId: 'code-academy-eed0d',
    storageBucket: 'code-academy-eed0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeP9iduW_RtACJL4ES6nBOHjKFjFeKJkI',
    appId: '1:109222307798:ios:208a868cf5af891ac42677',
    messagingSenderId: '109222307798',
    projectId: 'code-academy-eed0d',
    storageBucket: 'code-academy-eed0d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeP9iduW_RtACJL4ES6nBOHjKFjFeKJkI',
    appId: '1:109222307798:ios:5a2b78ef32c91d17c42677',
    messagingSenderId: '109222307798',
    projectId: 'code-academy-eed0d',
    storageBucket: 'code-academy-eed0d.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
